### ISSUE TITLE
 How to invalidate a cache view from multi-docker container.

### ISSUE THREAD

**Issue by abhinavsp0730** [Suor/django-cacheops#426]
I'm using docker-compose for hosting my django app.
And using nginx as reverse proxy.
```
version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis_db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  redis_db:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web
  
volumes:
  postgres_data:
  redisdata:
  static_volume:
```
And I'm trying to invalidate a view cache from another view like this,

```
order.invalidate("http://nginx:1337/order/demo", usr="demo")
``` 
But it's not working, Any help @Suor? Am I passing the url in right manner?
